config/routes.rb
Project1::Application.routes.draw do
  resources :posts

  get "sessions/new"
  post "sessions/create"
  get "sessions/destroy"
  resources :users
root to: 'users#new'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	default_scope order: 'created_at DESC'
	validates :content,length: { maximum: 140
	}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :name, presence: true
	validates :email, presence: true,uniqueness: true
	has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
  	@current_user ||=User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	def create
		@post=Post.new(post_params)
		@post.user_id=current_user.id

		if @post.save
			redirect_to current_user
		else
			flash[:error]="Oh No! :("
			redirect_to current_user
		end

	end
	private

   def post_params
    params.require(:post).permit(:content,:user_id)
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user= User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id]=user.id
  		redirect_to user, notice: "Logged  in!"

  	else
       flash[:error]="Wrong email or password"
       redirect_to root_url
  	end	
  end

  def destroy
  	session[:user_id]=nil
  	redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
	@user= User.new
end

def create
	@user = User.new(user_params)
	if @user.save
		session[:user_id] = @user.id
		redirect_to @user
 	else 
 		render 'new'
 	end		
end

def show
@user=User.find(params[:id])
@post=Post.new	
end

private

def user_params
	params.require(:user).permit(:name, :email, :password, :password_confirmation)
end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
	<%= link_to "Log Out",sessions_destroy_path %>
	<% else %>
	<%= link_to "Log In",sessions_new_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
	<%= f.text_field :name %>
	<%= f.text_field :email %>
	<%= f.password_field :password %>
	<%= f.password_field :password_confirmation %>
	<%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<% if current_user %>
<h1>Post something!</h1>
<%= form_for @post do |f| %>
<%= f.text_area :content %>
<%= f.submit "Post! :)" %>
<% end %>
<% end %>
<br>
<h1><%= @user.name %>'s Posts</h1>
<% @user.posts.each do |post| %>
<p><%= post.content %></p>
<%= time_ago_in_words(post.created_at) %>
<% end %>